### ISSUE TITLE
Shortcut to sd-card does not work

### ISSUE THREAD

**Issue by hsjpekka** [karip/harbour-file-browser#32]
Sdcard has moved to /run/media/nemo

**Comment by karip** [comment]
Thanks for pointing it out!

According to [this Jolla documentation](https://jolla.zendesk.com/hc/en-us/articles/201997993-What-kind-of-SD-cards-and-formats-are-supported-) there is a symbolic link from /media/sdcard/<uuid> to /run/media/nemo/<uuid>:

>Path to SD card
>
>Symbolic link (from Sailfish OS 2.2.0 onwards): 
>
>/media/sdcard/<uuid>
>
>Actual path (from Sailfish OS 2.2.0 onwards): 
>
>/run/media/nemo/<uuid>
>
>Both of the paths above can be used.

The current File Browser implementation does this:

1. It checks if "/media/sdcard" is a symbolic link, then it follows it (to "/run/media/nemo").
2. It reads the subfolders of "/media/sdcard" or the subfolders of the symbolic link ("/run/media/nemo").
3. It checks that the subfolders are mounted by checking that they are found in "/proc/mounts" (this step was [proposed by foolab](https://github.com/karip/harbour-file-browser/issues/2#issuecomment-37985028), because unmounted folders are left behind).

Are you saying that your phone has no symbolic link from "/media/sdcard" to the new SDCard folder "/run/media/nemo"?

I have a Jolla 1 phone with SFOS 2.2 and everything is working fine on it. It has a symbolic link from "media/sdcard" to "/run/media/nemo" and File Browser can find the SDCard.

**Comment by karip** [comment]
According to [this](https://together.jolla.com/question/186080/file-browser-and-sd-card/), some users have a symlink to "/run/media/nemo", but it is from "/media/sdcard/nemo" (not "/media/sdcard").

I'll try to create a fix according to that info. It would be nice it someone could test it on a device with a bad symlink before I submit the app to the Jolla Store. My phone has a proper symlink from "/media/sdcard", so I can't test it myself.

**Comment by karip** [comment]
I have created a pre-release version 1.7.2.1: https://github.com/karip/harbour-file-browser/releases/tag/v1.7.2.1

Can you test it by downloading the RPM file and installing it on your device?
armv7hl.rpm is for phones and i486.rpm is for tablets.

I won't submit it to the Jolla store until it has been tested.

**Comment by hsjpekka** [comment]
Sorry for the late answer. 
I have the symbolic link /media/sdcard/nemo.
I just installed version 1.7.2.1, and the sdcard is now visible. Thanks!

**Comment by karip** [comment]
Thanks for testing it! Version 1.7.3 is now available in Jolla Store with this fix.
