### ISSUE TITLE
In dir properties show size of folder's content (subdirs included)

### ISSUE THREAD

**Issue by Pohli** [karip/harbour-file-browser#33]
Title says it all. That feature would be very nice and the Size tag with the dash behind could be replaced by some real information. Possible to implement?

**Comment by karip** [comment]
Thanks for suggesting it!

Showing the size of files and subfolders is not trivial. There is no simple system function to get that information. The app would have to go through all files one by one and calculate their sum. That can take a long time, because folders may contain thousands of files.

It means that the calculation should be made in a background thread so that the user interface doesn't freeze. If the user exits the view, then the calculation should be stopped. All that makes the implementation non-trivial. Unfortunately, I don't currently have time to do such a large feature, but I keep this issue open if the situation changes.

If you want to see the size of folders, then you can already use the "Space Inspector" app in the Jolla Store.

**Comment by Pohli** [comment]
Okay, thanks for the hint to Space Inspector.

**Comment by karip** [comment]
I'm closing this issue as I assume that Space Inspector was good enough.
