### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by usbeehu** [karip/harbour-file-browser#38]
I think this file manager deserves a better icon that fits more with the default Sailfish apps icons.
I quickly made a vector icon that may better from this view. I wonder if you like it or not.

![sailfish-filemanager](https://user-images.githubusercontent.com/23268794/57156702-e691e880-6dde-11e9-944e-695d7650da6b.png)

[sailfish-filemanager.zip](https://github.com/karip/harbour-file-browser/files/3143072/sailfish-filemanager.zip)

**Comment by karip** [comment]
The original icon has been designed to be gray so that it matches the Jolla Terminal app icon, which is also gray. I consider File Browser to be a bit dangerous tool, just like Terminal, so I don't want to have an icon which looks too nice.

So, I think I'll keep the original icon. But, thanks for your suggestion.

**Comment by karip** [comment]
ichthyosaurus is the new maintainer of the File Browser app. This is the new repository of the app: https://github.com/ichthyosaurus/harbour-file-browser

Maybe you can open an issue there to see if they want to use the new icon?
